In [ ]:
import numpy as np

In [ ]:
x=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])
y=np.array([[1],[1],[0]])

In [ ]:
x       # 3 neurons in hidden layer 2 neurons in input layer

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [ ]:
y     #signum either 1 or 0

array([[1],
       [1],
       [0]])

In [ ]:
input_neurons=x.shape[1]
hidden_neurons=3
output_neurons=1

In [ ]:
input_neurons

4

In [ ]:
def sigmoid(x):
  return 1/(1+np.exp(-x))           #feedforward

def derivatesigmoid(x):
  return x*(x-1)                    #backpropagation

In [ ]:
weight_hidden=np.random.uniform(size=(input_neurons,hidden_neurons))  
weight_output=np.random.uniform(size=(hidden_neurons,output_neurons))
bias_hidden=np.random.uniform(size=(1,hidden_neurons))
bias_output=np.random.uniform(size=(1,output_neurons))

In [ ]:
weight_hidden

array([[0.65255445, 0.65969455, 0.68151068],
       [0.16539341, 0.95605743, 0.90882996],
       [0.61512638, 0.00389069, 0.83439883],
       [0.05995579, 0.90312655, 0.94105144]])

In [ ]:
weight_output

array([[0.0939612 ],
       [0.53445952],
       [0.06577688]])

In [ ]:
bias_hidden

array([[0.11593108, 0.50678413, 0.99592023]])

In [ ]:
bias_output

array([[0.30308906]])

In [ ]:
hidden_Layer=sigmoid(fx)
hidden_Layer

array([[0.79957046, 0.76321177, 0.92496698],
       [0.80900652, 0.88830031, 0.96931695],
       [0.58450148, 0.91419512, 0.94510126]])

In [ ]:
fx2=np.dot(hidden_Layer,weight_ouput)+bias_output
fx2

array([[2.1827521 ],
       [2.31237659],
       [2.15371109]])

In [ ]:
output_layer=sigmoid(fx2)
output_layer

array([[0.89868992],
       [0.90989689],
       [0.89601506]])

In [ ]:
# backpropagation

In [ ]:
loss=y-output_layer
loss

array([[ 0.10131008],
       [ 0.09010311],
       [-0.89601506]])

In [ ]:
slope=derivatesigmoid(output_layer)
slope

array([[-0.09104635],
       [-0.08198454],
       [-0.09317208]])

In [ ]:
delta=loss*slope
delta

array([[-0.00922391],
       [-0.00738706],
       [ 0.08348358]])

In [ ]:
lossHidden=np.dot(delta,weight_output.T)
lossHidden

array([[-0.00635498, -0.00619254, -0.00814124],
       [-0.00508945, -0.00495936, -0.00651999],
       [ 0.05751754,  0.05604729,  0.0736845 ]])

In [ ]:
slopeHidden=derivatesigmoid(hidden_Layer)
slopeHidden

array([[-0.16025754, -0.18071956, -0.06940307],
       [-0.15451497, -0.09922287, -0.0297416 ],
       [-0.2428595 , -0.07844241, -0.05188487]])

In [ ]:
deltaHidden=slopeHidden*lossHidden
deltaHidden

array([[ 0.00101843,  0.00111911,  0.00056503],
       [ 0.0007864 ,  0.00049208,  0.00019391],
       [-0.01396868, -0.00439648, -0.00382311]])

In [ ]:
# optimization

In [ ]:
weight_output=weight_output-np.dot(hidden_Layer.T,delta)*alpha
weight_output

array([[0.61736949],
       [0.5446655 ],
       [0.75494208]])

In [ ]:
weight_hidden=weight_hidden-np.dot(x.T,deltaHidden)
weight_hidden

array([[0.83478783, 0.70139421, 0.78994908],
       [0.2896452 , 0.88612726, 0.57850047],
       [0.267547  , 0.18818504, 0.33249604],
       [0.94464978, 0.8553993 , 0.72739744]])

In [ ]:
bias_output=bias_hidden-np.sum(delta)*alpha
bias_output

array([[0.98879252, 0.63023526, 0.14990771]])

In [ ]:
bias_hidden=bias_output-np.sum(deltaHidden)*alpha
bias_hidden

array([[0.98897265, 0.63041539, 0.15008784]])

In [ ]:
alpha=0.01
epochs=15000
weight_hidden=np.random.uniform(size=(input_neurons,hidden_neurons))  
weight_output=np.random.uniform(size=(hidden_neurons,output_neurons))
bias_hidden=np.random.uniform(size=(1,hidden_neurons))
bias_output=np.random.uniform(size=(1,output_neurons))
for i in range(epochs):
  fx=np.dot(x,weight_hidden)+bias_hidden
  hidden_Layer=sigmoid(fx)
  fx2=np.dot(hidden_Layer,weight_output)+bias_output
  hidden_Layer=sigmoid(fx2)



  loss=output_layer-y
  slope=derivatesigmoid(output_layer)
  delta=loss*slope



  lossHidden=np.dot(delta,weight_output.T)
  slopeHidden=derivatesigmoid(hidden_Layer)
  deltaHidden=slopeHidden*lossHidden




  weight_output=weight_output-np.dot(hidden_Layer.T,delta)*alpha
  weight_hidden=weight_hidden-np.dot(x.T,deltaHidden)
  bias_output=bias_hidden-np.sum(delta)*alpha
  bias_hidden=bias_output-np.sum(deltaHidden)*alpha



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [ ]:
output_layer

array([[0.89868992],
       [0.90989689],
       [0.89601506]])